### ISSUE TITLE
Ladspa: Label 'noise_suppressor_mono' not found in plugin 'librnnoise_ladspa.so

### ISSUE THREAD

**Issue by RXAldreezee** [malteger/rnnoise_loader#1]
pi@raspberrypi:~/Downloads/rnnoise_loader-master $ bash rnnoise_loader
rnnoise_loader: line 173: analyseplugin: command not found
Ladspa: Label 'noise_suppressor_mono' not found in plugin 'librnnoise_ladspa.so

I'm using Raspberry Pi 4, I have compiled the Werman plugin here, it doesn't work, can you please help? Thank you.

**Comment by RXAldreezee** [comment]
I typed the ff:
pi@raspberrypi:~/Downloads/rnnoise_loader-master $ bash rnnoise_loader -f
Loading RNNoise for source alsa_input.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-mono

It works but sounds bad, why is it?

**Comment by malteger** [comment]
The first issue was caused by the missing `analyseplugin` which is at least for archlinux included in the ladspa package.

As it works with `-f`, it looks like it is working in principle. The plugin itself causes quite some CPU load, so it might be too much for a RaspberryPi, I have not tested that. You might want to have a look at the system load while using that plugin to see if that is the issue.

**Comment by malteger** [comment]
(Closed here as the performance is out of scope for this loading script)
